/**
 * Soundboard clips and their playback.
 *
 * Playing a sound does not publish an extra audio track: the sender
 * broadcasts a LiveKit data packet naming the clip, and every participant
 * (including the sender) plays it locally. That keeps a soundboard hit at
 * full quality regardless of the mic codec, costs no extra upstream
 * bandwidth, and means a deafened listener can simply not play it.
 *
 * Built-in clips are generated by `scripts/generate-default-sounds.mjs` and
 * served from `public/sounds/`; community clips are uploaded to Convex file
 * storage (see convex/soundboard.ts) and referenced by absolute URL.
 */

export interface SoundboardClip {
  /** Stable id — `builtin:<name>` or the Convex document id. */
  id: string;
  name: string;
  emoji: string;
  /** Absolute or app-relative URL of the audio file. */
  url: string;
  builtin: boolean;
}

/** Clips that ship with the app and are available in every call. */
export const BUILTIN_SOUNDS: SoundboardClip[] = [
  { id: "builtin:ping", name: "Ping", emoji: "🔔", url: "/sounds/ping.wav", builtin: true },
  { id: "builtin:boop", name: "Boop", emoji: "👉", url: "/sounds/boop.wav", builtin: true },
  { id: "builtin:pop", name: "Pop", emoji: "🫧", url: "/sounds/pop.wav", builtin: true },
  { id: "builtin:chime", name: "Chime", emoji: "✨", url: "/sounds/chime.wav", builtin: true },
  { id: "builtin:buzz", name: "Buzz", emoji: "❌", url: "/sounds/buzz.wav", builtin: true },
  { id: "builtin:zap", name: "Zap", emoji: "⚡", url: "/sounds/zap.wav", builtin: true },
  { id: "builtin:horn", name: "Horn", emoji: "📣", url: "/sounds/horn.wav", builtin: true },
  { id: "builtin:drumroll", name: "Drumroll", emoji: "🥁", url: "/sounds/drumroll.wav", builtin: true },
];

export function findBuiltinSound(id: string): SoundboardClip | undefined {
  return BUILTIN_SOUNDS.find((s) => s.id === id);
}

/** Wire format of the LiveKit data packet a soundboard hit broadcasts. */
export interface SoundboardPacket {
  kind: "soundboard";
  soundId: string;
  /** Only sent for uploaded clips — built-ins resolve from `soundId` alone,
   * so a receiver never has to trust a URL it can already look up. */
  url?: string;
  name?: string;
}

export const SOUNDBOARD_TOPIC = "soundboard";

/** Separate topic from a soundboard press so a join sound can't be mistaken
 * for one — they're played at the same volume but mean different things. */
export const JOIN_SOUND_TOPIC = "joinsound";

/** Wire format of the packet a joiner broadcasts on arrival. */
export interface JoinSoundPacket {
  kind: "joinsound";
  soundId: string;
  /** Only for uploaded clips; built-ins resolve from `soundId`. */
  url?: string;
}

/**
 * Resolve a join sound to a playable URL.
 *
 * Built-ins are looked up locally from the id, so a packet can never point a
 * listener at an arbitrary URL for a clip they already ship; an uploaded clip
 * has to supply one, which is then range-checked like any other.
 */
export function resolveJoinSoundUrl(soundId: string, url?: string): string | null {
  const builtin = findBuiltinSound(soundId);
  if (builtin) return builtin.url;
  return url && isPlayableSoundUrl(url) ? url : null;
}

/** Cheapest safety net against a clip URL from a data packet pointing
 * somewhere unexpected: only same-origin paths and https URLs play. */
export function isPlayableSoundUrl(url: string): boolean {
  if (url.startsWith("/")) return true;
  try {
    return new URL(url).protocol === "https:";
  } catch {
    return false;
  }
}

/** Concurrent playbacks, so one person spamming can't stack up unbounded
 * audio elements. */
const MAX_CONCURRENT = 4;
const playing = new Set<HTMLAudioElement>();

/**
 * Play a clip through the local speakers at `volume`, optionally pinned to a
 * specific output device. No-ops while deafened is handled by the caller —
 * this function always plays what it's given.
 */
export async function playSound(
  url: string,
  options: {
    volume?: number;
    outputDeviceId?: string;
    /** Fired once when playback finishes — or immediately if it never
     * starts, so a caller waiting on it is never left hanging. */
    onEnded?: () => void;
  } = {}
): Promise<void> {
  if (typeof window === "undefined" || !isPlayableSoundUrl(url)) {
    options.onEnded?.();
    return;
  }
  if (playing.size >= MAX_CONCURRENT) {
    options.onEnded?.();
    return;
  }

  const audio = new Audio(url);
  audio.volume = Math.max(0, Math.min(1, options.volume ?? 1));

  const sinkId = options.outputDeviceId;
  if (sinkId && typeof (audio as { setSinkId?: unknown }).setSinkId === "function") {
    await (audio as HTMLAudioElement & { setSinkId(id: string): Promise<void> })
      .setSinkId(sinkId)
      .catch(() => {
        // Device disappeared or isn't selectable — fall back to the default.
      });
  }

  playing.add(audio);
  let ended = false;
  const cleanup = () => {
    playing.delete(audio);
    audio.remove();
    if (ended) return;
    ended = true;
    options.onEnded?.();
  };
  audio.addEventListener("ended", cleanup, { once: true });
  audio.addEventListener("error", cleanup, { once: true });

  try {
    await audio.play();
  } catch {
    cleanup();
  }
}

/** Stop every clip currently playing — used when the user deafens mid-clip. */
export function stopAllSounds(): void {
  for (const audio of playing) {
    audio.pause();
    // Firing `ended` releases whatever was scoped to this clip — without it,
    // deafening mid-clip would strand a highlight until its safety cap.
    audio.dispatchEvent(new Event("ended"));
    audio.remove();
  }
  playing.clear();
}

/**
 * The length of a clip in ms, read from metadata without playing it.
 *
 * Used for listeners who are deafened: they don't hear the clip, but the
 * highlight showing *who played it* should still last as long as everyone
 * else's does. Resolves null if the metadata never arrives.
 */
export function measureSoundDuration(url: string): Promise<number | null> {
  if (typeof window === "undefined" || !isPlayableSoundUrl(url)) return Promise.resolve(null);
  return new Promise((resolve) => {
    const audio = new Audio();
    audio.preload = "metadata";
    const done = (value: number | null) => {
      audio.removeAttribute("src");
      resolve(value);
    };
    audio.addEventListener(
      "loadedmetadata",
      () => done(Number.isFinite(audio.duration) ? Math.round(audio.duration * 1000) : null),
      { once: true }
    );
    audio.addEventListener("error", () => done(null), { once: true });
    audio.src = url;
  });
}

// --- who's playing a sound right now ---------------------------------------

/** Fallback highlight length when a clip's real duration can't be determined,
 * and the ceiling on any single highlight so a wedged element can't leave a
 * ring on forever. */
export const SOUNDBOARD_FALLBACK_MS = 1500;
const SOUNDBOARD_MAX_MS = 30_000;

type ActivityListener = (identity: string, active: boolean) => void;

const activityListeners = new Set<ActivityListener>();
/** Concurrent clips per identity, so one ending doesn't clear the highlight
 * while another of theirs is still playing. */
const activeCounts = new Map<string, number>();

function emitActivity(identity: string, active: boolean): void {
  for (const listener of activityListeners) {
    try {
      listener(identity, active);
    } catch (err) {
      console.warn("[soundboard] activity listener threw", err);
    }
  }
}

/**
 * Mark `identity` as playing a soundboard clip, returning the function that
 * ends it. Callers bind that to the clip's actual playback, so the highlight
 * lasts exactly as long as the sound does.
 *
 * A tiny emitter rather than deriving this from LiveKit's `DataReceived`
 * where it's needed: the SFU doesn't loop a data packet back to its sender,
 * so the person who pressed the button would never light up. `useRoom` calls
 * this for both the remote packet and the local press, and everything that
 * renders a highlight subscribes here — the call tiles and the channel
 * participant list get the same signal from one place.
 */
export function beginSoundboardActivity(identity: string): () => void {
  const count = (activeCounts.get(identity) ?? 0) + 1;
  activeCounts.set(identity, count);
  if (count === 1) emitActivity(identity, true);

  let released = false;
  const release = () => {
    if (released) return;
    released = true;
    clearTimeout(cap);
    const remaining = (activeCounts.get(identity) ?? 1) - 1;
    if (remaining > 0) {
      activeCounts.set(identity, remaining);
      return;
    }
    activeCounts.delete(identity);
    emitActivity(identity, false);
  };

  const cap = setTimeout(release, SOUNDBOARD_MAX_MS);
  return release;
}

export function onSoundboardActivity(listener: ActivityListener): () => void {
  activityListeners.add(listener);
  return () => activityListeners.delete(listener);
}
