/**
 * The app's own sound effects — join/leave, mute, deafen, camera, messages,
 * ringing.
 *
 * Separate from `soundboard.ts`, which is user-triggered content shared with
 * a room. These are feedback for the local user's own actions, so they read
 * their own volume preference and are never broadcast.
 *
 * Clips are generated by `scripts/generate-ui-sounds.mjs`; the names here are
 * the file names in `public/sounds/ui/`.
 */

export const UI_SOUNDS = {
  callJoin: "call-join",
  callLeave: "call-leave",
  screenShareStart: "screenshare-start",
  screenShareStop: "screenshare-stop",
  /** Someone started / stopped watching a stream *you* are publishing. */
  viewerJoin: "viewer-join",
  viewerLeave: "viewer-leave",
  mute: "mute",
  unmute: "unmute",
  deafen: "deafen",
  undeafen: "undeafen",
  cameraOn: "camera-on",
  cameraOff: "camera-off",
  message: "message",
  ring: "ring",
  /** Easter egg — see `pickRingSound`. */
  ringAlt: "ring_2_percent",
  ringOutgoing: "ring-outgoing",
} as const;

export type UiSound = keyof typeof UI_SOUNDS;

/** How often the alternate ringtone turns up instead of the usual one. */
const RING_ALT_CHANCE = 0.02;

/**
 * Which ringtone this particular incoming call gets: the normal one, or —
 * two times in a hundred — the alternate.
 *
 * Rolled once per call by the caller and held for its duration, so the
 * ringtone can't change under you when the volume or output device is
 * adjusted mid-ring.
 */
export function pickRingSound(): UiSound {
  return Math.random() < RING_ALT_CHANCE ? "ringAlt" : "ring";
}

function urlFor(sound: UiSound): string {
  return `/sounds/ui/${UI_SOUNDS[sound]}.wav`;
}

export interface UiSoundOptions {
  /** 0–1. Below ~0.01 nothing is played at all. */
  volume?: number;
  /** Output device id; falls back to the system default. */
  outputDeviceId?: string;
}

async function applySink(audio: HTMLAudioElement, outputDeviceId?: string): Promise<void> {
  if (!outputDeviceId) return;
  const withSink = audio as HTMLAudioElement & { setSinkId?: (id: string) => Promise<void> };
  if (typeof withSink.setSinkId !== "function") return;
  // Device disappeared or isn't selectable — fall back to the default rather
  // than dropping the sound.
  await withSink.setSinkId(outputDeviceId).catch(() => {});
}

/** Play a one-shot effect. Fire-and-forget; failures are silent by design —
 * a UI sound that can't play should never interrupt the action it accompanies. */
export function playUiSound(sound: UiSound, options: UiSoundOptions = {}): void {
  if (typeof window === "undefined") return;
  const volume = options.volume ?? 1;
  if (volume < 0.01) return;

  const audio = new Audio(urlFor(sound));
  audio.volume = Math.min(1, volume);
  void applySink(audio, options.outputDeviceId).then(() => audio.play().catch(() => {}));
}

/**
 * Start a looping effect (the ringtones) and return the function that stops
 * it. Safe to call the stopper more than once.
 */
export function startUiSoundLoop(sound: UiSound, options: UiSoundOptions = {}): () => void {
  if (typeof window === "undefined") return () => {};
  const volume = options.volume ?? 1;
  if (volume < 0.01) return () => {};

  const audio = new Audio(urlFor(sound));
  audio.loop = true;
  audio.volume = Math.min(1, volume);

  let stopped = false;
  void applySink(audio, options.outputDeviceId).then(() => {
    // The stopper may already have run while the sink was resolving.
    if (!stopped) void audio.play().catch(() => {});
  });

  return () => {
    if (stopped) return;
    stopped = true;
    audio.pause();
    audio.remove();
  };
}
