import { ROUTES, matchRoute } from "../../convex/lib/botRoutes";
let f = 0, p = 0; const ok = (n: string, c: boolean, d?: unknown) => { c ? p++ : (f++, console.log("FAIL", n, JSON.stringify(d))); };
const m = (method: string, path: string) => { const r = matchRoute(method, path); return r && "matched" in r ? r.matched : r; };
ok("every route has a unique method+path", new Set(ROUTES.map((r) => r.method + r.path)).size === ROUTES.length);
ok("every route has a unique op", new Set(ROUTES.map((r) => r.op)).size === ROUTES.length);
ok("params are extracted", (m("GET", "/channels/abc/messages/xyz") as any).params.messageId === "xyz" && (m("GET", "/channels/abc/messages/xyz") as any).route.op === "message.get");
ok("literal beats param: bulk-delete", (m("POST", "/channels/c/messages/bulk-delete") as any).route.op === "message.bulkDelete");
ok("…but only for the method it's registered for", (m("GET", "/channels/c/messages/bulk-delete") as any).route.op === "message.get");
ok("emoji param is decoded", (m("PUT", "/channels/c/messages/m/reactions/%F0%9F%91%8D") as any).params.emoji === "👍");
ok("clear vs remove reaction", (m("DELETE", "/channels/c/messages/m/reactions") as any).route.op === "reaction.clear" && (m("DELETE", "/channels/c/messages/m/reactions/x") as any).route.op === "reaction.remove");
ok("wrong method → 405 with the allowed ones", JSON.stringify([...(m("POST", "/me") as any).methodNotAllowed].sort()) === '["GET","PATCH"]');
ok("unknown path → null", m("GET", "/nope") === null && m("GET", "/channels/c/nope") === null);
ok("trailing slash tolerated", (m("GET", "/me/") as any).route.op === "me");
ok("bad percent-encoding doesn't match (no throw)", m("GET", "/channels/%E0%A4%A/messages") === null);
ok("over-long param refused", m("GET", "/channels/" + "x".repeat(201)) === null);
ok("empty segments collapse, never create an empty param", m("GET", "/channels//messages") === null || (m("GET", "/channels//messages") as any).params?.channelId !== "");
ok("ids with dots/slashes can't smuggle a path", m("GET", "/channels/..%2F..%2Fme/messages") !== null && (m("GET", "/channels/..%2F..%2Fme/messages") as any).params.channelId === "../../me");
ok("ops cover the documented surface", ["message.send", "voice.join", "channel.create", "role.create", "ban.add", "emoji.create", "sound.create", "presence.set", "dm.send"].every((o) => ROUTES.some((r) => r.op === o)));
console.log(f ? `${f} FAILED (${p} passed)` : `ALL PASSED (${p})`); process.exit(f ? 1 : 0);
