#!/usr/bin/env bun
/**
 * Compiles Studio's written guides (Markdown, in src/studio/docs/content) into one TypeScript
 * module the app imports: src/studio/docs/built-in.generated.ts.
 *
 * Why a module and not the .md files themselves: the app is a static export, and importing Markdown
 * as text isn't something Next's bundlers do without extra loaders. A generated file is plain data,
 * searchable synchronously, and works offline. It is committed, and a test (scripts/tests/guides.test.mts)
 * fails if it is out of date, so a guide can't be edited without its compiled copy following.
 *
 *   bun scripts/build-guides.mjs           write the module
 *   bun scripts/build-guides.mjs --check   exit 1 if the module is out of date
 *
 * A guide is `content/<folder>/<name>.md` and its address is `<folder>/<name>`:
 *
 *   ---
 *   title: How bots work
 *   topic: bots              general | canvas | extensions | bots
 *   kind: guide              guide | article | reference
 *   section: Bots            the group it is listed under
 *   order: 10                lowest first, within its section
 *   summary: One sentence.
 *   ---
 *   # Markdown…
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const CONTENT = join(root, "src/studio/docs/content");
export const OUT = join(root, "src/studio/docs/built-in.generated.ts");

const KEYS = ["title", "topic", "kind", "section", "order", "summary"];

function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name))) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (e.name.endsWith(".md")) out.push(p);
  }
  return out;
}

/** `---\nkey: value\n---\nbody` → { meta, body }. Throws a sentence saying which file is wrong. */
export function parseGuide(file, raw) {
  const m = /^---\n([\s\S]*?)\n---\n?([\s\S]*)$/.exec(raw.replace(/\r\n?/g, "\n"));
  if (!m) throw new Error(`${file}: starts without a --- front matter block.`);
  const meta = {};
  for (const line of m[1].split("\n")) {
    if (!line.trim()) continue;
    const kv = /^([a-z]+):\s*(.*)$/.exec(line);
    if (!kv || !KEYS.includes(kv[1])) throw new Error(`${file}: unknown front matter line “${line}”. Use ${KEYS.join(", ")}.`);
    // A value may be quoted (needed when it contains a colon); matching quotes around it are not part of it.
    const v = kv[2].trim();
    meta[kv[1]] = /^(["']).*\1$/.test(v) && v.length >= 2 ? v.slice(1, -1) : v;
  }
  for (const k of KEYS) if (meta[k] === undefined || meta[k] === "") throw new Error(`${file}: front matter is missing “${k}”.`);
  if (!Number.isFinite(Number(meta.order))) throw new Error(`${file}: order isn't a number.`);
  return { meta, body: m[2].replace(/^\n+/, "").replace(/\s+$/, "") + "\n" };
}

export function readGuides() {
  if (!existsSync(CONTENT)) return [];
  return walk(CONTENT).map((file) => {
    const slug = relative(CONTENT, file).split(sep).join("/").replace(/\.md$/, "");
    const { meta, body } = parseGuide(slug, readFileSync(file, "utf8"));
    return { slug, title: meta.title, topic: meta.topic, kind: meta.kind, section: meta.section, summary: meta.summary, order: Number(meta.order), body };
  });
}

/** The text of the generated module. */
export function renderModule(pages) {
  return `// GENERATED by scripts/build-guides.mjs from src/studio/docs/content/**/*.md — do not edit by hand.
// Edit the Markdown, then run \`bun scripts/build-guides.mjs\` (it also runs with the dev and build scripts).
import type { PageData } from "@/studio/docs/pages";

export const BUILT_IN_GUIDES: PageData[] = ${JSON.stringify(pages, null, 2)};
`;
}

export function writeGuides() {
  const text = renderModule(readGuides());
  const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
  if (current !== text) {
    writeFileSync(OUT, text);
    return true;
  }
  return false;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  if (process.argv.includes("--check")) {
    const stale = (existsSync(OUT) ? readFileSync(OUT, "utf8") : "") !== renderModule(readGuides());
    if (stale) {
      console.error("[guides] built-in.generated.ts is out of date. Run: bun scripts/build-guides.mjs");
      process.exit(1);
    }
    console.log("[guides] up to date");
  } else {
    console.log(writeGuides() ? "[guides] wrote src/studio/docs/built-in.generated.ts" : "[guides] up to date");
  }
}
